//! TDM contract crate — the single source of truth for the Typed Decision Model
//! wire contract (plan §5, D7).
//!
//! Everything here is public API:
//!
//! - [`PrimitiveKind`] / [`Primitive`]: the three judged primitives (choice, noul, score).
//! - [`Question`] / [`DecisionRequest`]: what a caller asks.
//! - [`Answer`] / [`AnswerValue`] / [`DecisionResult`]: what a provider returns.
//! - [`Capabilities`] / [`HealthReport`]: provider self-description.
//! - [`DecisionProvider`]: the semantic, capability-neutral provider trait (ADR-0003).
//! - [`TdmError`] / [`ValidationError`]: the error taxonomy driving retry /
//!   circuit-breaker / escalation policy.
//!
//! TypeScript bindings are generated by ts-rs on `cargo test` into
//! `adapters/tdm-contract/src/generated/` (export dir configured in
//! `.cargo/config.toml`); JSON Schemas are dumped by schemars
//! into `adapters/tdm-contract/schema/`. Both are committed artifacts.

use async_trait::async_trait;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

/// Coarse capability class of a [`Primitive`], used for provider negotiation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema, TS)]
#[serde(rename_all = "lowercase")]
#[ts(export, rename_all = "lowercase")]
pub enum PrimitiveKind {
    Choice,
    Noul,
    Score,
}

/// The three judged primitives.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema, TS)]
#[serde(tag = "type", rename_all = "lowercase")]
#[ts(export, rename_all = "lowercase")]
pub enum Primitive {
    /// Single choice: winning label plus the competing probability distribution.
    Choice {
        /// Candidate options (1..=255).
        options: Vec<String>,
    },
    /// Boolean judgment: P(yes). Carries no separate confidence.
    Noul,
    /// Ordered score level: chosen level plus the level distribution.
    Score {
        /// Ordered level labels (2..=10).
        levels: Vec<String>,
    },
}

/// A single question to judge. `id` is a code-side identifier and is never sent
/// to the model; `instructions` must be semantically self-contained.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, rename_all = "camelCase")]
pub struct Question {
    /// Code-side identifier; echoed back in [`Answer::id`].
    pub id: String,
    /// Judgment instructions (complete self-contained semantics).
    pub instructions: String,
    /// Which primitive to judge.
    pub primitive: Primitive,
}

/// One batch of independent questions sharing the same decision state.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, rename_all = "camelCase")]
pub struct DecisionRequest {
    /// JSON value carrying all context required for the judgments.
    pub state: serde_json::Value,
    /// Independent questions, judged in parallel against `state`.
    pub questions: Vec<Question>,
}

/// Typed answer payload; discriminates on the judged primitive.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema, TS)]
#[serde(tag = "type", rename_all = "lowercase")]
#[ts(export, rename_all = "lowercase")]
pub enum AnswerValue {
    /// Winning label plus the probability distribution over options.
    Choice {
        /// Chosen option label.
        label: String,
        /// Competing distribution: (option label, probability) pairs.
        distribution: Vec<(String, f64)>,
    },
    /// P(yes) for a boolean judgment.
    Noul {
        /// Probability that the answer is "yes", in `0.0..=1.0`.
        probability: f64,
    },
    /// Chosen level plus the distribution over levels.
    Score {
        /// Chosen level label.
        level: String,
        /// Weighted score derived from the level distribution.
        weighted: f64,
        /// Distribution: (level label, probability) pairs.
        distribution: Vec<(String, f64)>,
    },
}

/// Answer to a single [`Question`].
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, rename_all = "camelCase")]
pub struct Answer {
    /// Echoes [`Question::id`].
    pub id: String,
    /// Typed payload.
    pub value: AnswerValue,
    /// Distribution concentration; always `None` for noul.
    pub confidence: Option<f64>,
}

/// Token usage of a judgment call (cost accounting input).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, rename_all = "camelCase")]
pub struct Usage {
    /// Input tokens consumed.
    pub input_tokens: u64,
    /// Output tokens produced.
    pub output_tokens: u64,
}

/// Which provider answered, and with which model.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, rename_all = "camelCase")]
pub struct ProviderMeta {
    /// Stable provider identifier (e.g. `"jev"`, `"mock"`).
    pub id: String,
    /// Concrete model identifier, when the provider has one.
    pub model: Option<String>,
}

/// Full result of a judgment batch.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, rename_all = "camelCase")]
pub struct DecisionResult {
    /// One answer per request question, in the same order.
    pub answers: Vec<Answer>,
    /// Token usage (cost accounting input).
    pub usage: Usage,
    /// Which provider produced this result.
    pub provider: ProviderMeta,
    /// End-to-end latency in milliseconds.
    pub latency_ms: u64,
}

/// Provider capability envelope used for routing negotiation (ADR-0003).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, rename_all = "camelCase")]
pub struct Capabilities {
    /// Primitives the provider can judge.
    pub primitives: Vec<PrimitiveKind>,
    /// Whether the provider supports parallel question batches.
    pub batch: bool,
    /// Maximum accepted [`DecisionRequest::state`] size in bytes.
    pub max_state_bytes: usize,
}

/// Liveness / connectivity probe result.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, rename_all = "camelCase")]
pub struct HealthReport {
    /// Whether the provider is healthy.
    pub ok: bool,
    /// Probe latency in milliseconds.
    pub latency_ms: u64,
    /// Optional human-readable detail.
    pub detail: Option<String>,
    /// Optional provider/API version string.
    pub version: Option<String>,
}

/// Error taxonomy driving retry / circuit-breaker / escalation policy.
///
/// - [`TdmError::Network`]: retryable with exponential backoff.
/// - [`TdmError::Server`]: limited retries.
/// - [`TdmError::Client`]: never retried; surfaced as-is.
/// - [`TdmError::Quality`]: no retry; escalate to human/adapter policy.
/// - [`TdmError::Unsupported`]: capability negotiation failure.
#[derive(Debug, Clone, PartialEq, thiserror::Error)]
pub enum TdmError {
    /// Transport-level failure.
    #[error("network error: {message}")]
    Network {
        /// Failure description.
        message: String,
    },
    /// Provider-side failure (5xx-class).
    #[error("server error (status {status}): {message}")]
    Server {
        /// HTTP status.
        status: u16,
        /// Failure description.
        message: String,
    },
    /// Caller-side failure (4xx-class).
    #[error("client error (status {status}, code {code:?}): {message}")]
    Client {
        /// HTTP status.
        status: u16,
        /// Machine-readable error code, when the provider emits one.
        code: Option<String>,
        /// Failure description.
        message: String,
    },
    /// Provider answered but the result is unusable.
    #[error("quality failure: {detail}")]
    Quality {
        /// Why the result failed the quality bar.
        detail: String,
    },
    /// Requested primitive is not in the provider's capabilities.
    #[error("unsupported primitive: {primitive:?}")]
    Unsupported {
        /// The primitive that could not be negotiated.
        primitive: PrimitiveKind,
    },
}

impl TdmError {
    /// Whether the failed operation may be retried: network and server errors only.
    pub fn is_retryable(&self) -> bool {
        matches!(self, Self::Network { .. } | Self::Server { .. })
    }
}

/// Request-shape violations detected locally, before any provider call.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum ValidationError {
    /// Choice with zero options.
    #[error("choice options must be non-empty")]
    EmptyOptions,
    /// Choice exceeding the 255-option ceiling.
    #[error("too many choice options (max {max})")]
    TooManyOptions {
        /// Ceiling that was exceeded (255).
        max: usize,
    },
    /// Score outside the 2..=10 level range.
    #[error("invalid score level count (min {min}, max {max})")]
    InvalidLevelCount {
        /// Minimum level count (2).
        min: usize,
        /// Maximum level count (10).
        max: usize,
    },
    /// Empty instructions.
    #[error("instructions must be non-empty")]
    EmptyInstructions,
}

impl Question {
    /// Validates the question shape: choice 1..=255 options, score 2..=10
    /// levels, non-empty instructions.
    ///
    /// # Errors
    /// Returns [`ValidationError`] describing the first violated bound.
    pub fn validate(&self) -> Result<(), ValidationError> {
        if self.instructions.is_empty() {
            return Err(ValidationError::EmptyInstructions);
        }
        match &self.primitive {
            Primitive::Choice { options } => {
                if options.is_empty() {
                    return Err(ValidationError::EmptyOptions);
                }
                if options.len() > 255 {
                    return Err(ValidationError::TooManyOptions { max: 255 });
                }
            }
            Primitive::Noul => {}
            Primitive::Score { levels } => {
                if !(2..=10).contains(&levels.len()) {
                    return Err(ValidationError::InvalidLevelCount { min: 2, max: 10 });
                }
            }
        }
        Ok(())
    }
}

/// Semantic, capability-neutral provider interface (ADR-0003).
///
/// Implementations must be safe to share across threads; the runtime routes
/// through `Arc<dyn DecisionProvider>`.
#[async_trait]
pub trait DecisionProvider: Send + Sync {
    /// Stable provider identifier (e.g. `"jev"`, `"mock"`).
    fn id(&self) -> &str;

    /// Advertised capability envelope.
    fn capabilities(&self) -> &Capabilities;

    /// Judge one batch of questions against the given state.
    ///
    /// # Errors
    /// [`TdmError`] per the retry/escalation taxonomy.
    async fn judge(&self, req: DecisionRequest) -> Result<DecisionResult, TdmError>;

    /// Liveness / connectivity probe.
    async fn health(&self) -> HealthReport;
}

#[cfg(test)]
mod tests {
    use super::*;
    use schemars::schema_for;
    use std::fs;
    use std::path::Path;

    fn choice_question(n_options: usize) -> Question {
        Question {
            id: "q1".into(),
            instructions: "pick one".into(),
            primitive: Primitive::Choice {
                options: (0..n_options).map(|i| format!("option-{i}")).collect(),
            },
        }
    }

    fn score_question(n_levels: usize) -> Question {
        Question {
            id: "q2".into(),
            instructions: "rate it".into(),
            primitive: Primitive::Score {
                levels: (0..n_levels).map(|i| format!("L{i}")).collect(),
            },
        }
    }

    fn sample_request() -> DecisionRequest {
        DecisionRequest {
            state: serde_json::json!({ "repo": "tdm", "files_changed": 3 }),
            questions: vec![
                choice_question(2),
                Question {
                    id: "q3".into(),
                    instructions: "is it safe?".into(),
                    primitive: Primitive::Noul,
                },
            ],
        }
    }

    fn sample_result() -> DecisionResult {
        DecisionResult {
            answers: vec![
                Answer {
                    id: "q1".into(),
                    value: AnswerValue::Choice {
                        label: "option-1".into(),
                        distribution: vec![("option-0".into(), 0.3), ("option-1".into(), 0.7)],
                    },
                    confidence: Some(0.4),
                },
                Answer {
                    id: "q3".into(),
                    value: AnswerValue::Noul { probability: 0.92 },
                    confidence: None,
                },
            ],
            usage: Usage {
                input_tokens: 128,
                output_tokens: 32,
            },
            provider: ProviderMeta {
                id: "mock".into(),
                model: Some("mock-1".into()),
            },
            latency_ms: 42,
        }
    }

    #[test]
    fn wire_tags_are_lowercase() {
        let choice = serde_json::to_value(Primitive::Choice {
            options: vec!["a".into(), "b".into()],
        })
        .unwrap();
        assert_eq!(choice["type"], "choice");
        assert_eq!(
            serde_json::to_value(Primitive::Noul).unwrap()["type"],
            "noul"
        );
        let score = serde_json::to_value(Primitive::Score {
            levels: vec!["L0".into(), "L1".into()],
        })
        .unwrap();
        assert_eq!(score["type"], "score");

        let av = serde_json::to_value(AnswerValue::Noul { probability: 0.7 }).unwrap();
        assert_eq!(av["type"], "noul");

        assert_eq!(
            serde_json::to_value(PrimitiveKind::Choice).unwrap(),
            "choice"
        );
        assert_eq!(serde_json::to_value(PrimitiveKind::Noul).unwrap(), "noul");
        assert_eq!(serde_json::to_value(PrimitiveKind::Score).unwrap(), "score");
    }

    #[test]
    fn decision_request_roundtrips_with_camel_case() {
        let req = sample_request();
        let json = serde_json::to_value(&req).unwrap();
        assert!(json.get("questions").is_some(), "wire format is camelCase");
        let back: DecisionRequest = serde_json::from_value(json).unwrap();
        assert_eq!(back, req);
    }

    #[test]
    fn decision_result_roundtrips_with_camel_case() {
        let result = sample_result();
        let json = serde_json::to_value(&result).unwrap();
        assert_eq!(json["usage"]["inputTokens"], 128);
        assert_eq!(json["latencyMs"], 42);
        assert_eq!(json["provider"]["model"], "mock-1");
        assert_eq!(json["answers"][0]["value"]["type"], "choice");
        assert_eq!(json["answers"][1]["confidence"], serde_json::Value::Null);
        let back: DecisionResult = serde_json::from_value(json).unwrap();
        assert_eq!(back, result);
    }

    #[test]
    fn capabilities_and_health_roundtrip() {
        let caps = Capabilities {
            primitives: vec![
                PrimitiveKind::Choice,
                PrimitiveKind::Noul,
                PrimitiveKind::Score,
            ],
            batch: true,
            max_state_bytes: 1 << 20,
        };
        let json = serde_json::to_value(&caps).unwrap();
        assert_eq!(json["maxStateBytes"], 1 << 20);
        let caps_back: Capabilities = serde_json::from_value(json).unwrap();
        assert_eq!(caps_back, caps);

        let health = HealthReport {
            ok: true,
            latency_ms: 7,
            detail: None,
            version: Some("v1".into()),
        };
        let json = serde_json::to_value(&health).unwrap();
        assert_eq!(json["latencyMs"], 7);
        let health_back: HealthReport = serde_json::from_value(json).unwrap();
        assert_eq!(health_back, health);
    }

    #[test]
    fn validate_choice_boundaries() {
        assert_eq!(
            choice_question(0).validate(),
            Err(ValidationError::EmptyOptions)
        );
        assert_eq!(choice_question(1).validate(), Ok(()));
        assert_eq!(choice_question(255).validate(), Ok(()));
        assert_eq!(
            choice_question(256).validate(),
            Err(ValidationError::TooManyOptions { max: 255 })
        );
    }

    #[test]
    fn validate_score_boundaries() {
        for n in [1, 11] {
            assert_eq!(
                score_question(n).validate(),
                Err(ValidationError::InvalidLevelCount { min: 2, max: 10 })
            );
        }
        for n in [2, 10] {
            assert_eq!(score_question(n).validate(), Ok(()));
        }
    }

    #[test]
    fn validate_rejects_empty_instructions() {
        let q = Question {
            id: "q".into(),
            instructions: String::new(),
            primitive: Primitive::Noul,
        };
        assert_eq!(q.validate(), Err(ValidationError::EmptyInstructions));
    }

    #[test]
    fn noul_validates_without_levels() {
        let q = Question {
            id: "q".into(),
            instructions: "ok".into(),
            primitive: Primitive::Noul,
        };
        assert_eq!(q.validate(), Ok(()));
    }

    #[test]
    fn error_retryability_follows_taxonomy() {
        assert!(
            TdmError::Network {
                message: "x".into()
            }
            .is_retryable()
        );
        assert!(
            TdmError::Server {
                status: 503,
                message: "x".into()
            }
            .is_retryable()
        );
        assert!(
            !TdmError::Client {
                status: 400,
                code: Some("bad_request".into()),
                message: "x".into()
            }
            .is_retryable()
        );
        assert!(!TdmError::Quality { detail: "x".into() }.is_retryable());
        assert!(
            !TdmError::Unsupported {
                primitive: PrimitiveKind::Score
            }
            .is_retryable()
        );
    }

    /// Dumps JSON Schemas for every contract type into
    /// `adapters/tdm-contract/schema/` (committed artifacts).
    #[test]
    fn export_json_schemas() {
        let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../adapters/tdm-contract/schema");
        fs::create_dir_all(&dir).unwrap();

        let schemas = [
            ("Answer", schema_for!(Answer)),
            ("AnswerValue", schema_for!(AnswerValue)),
            ("Capabilities", schema_for!(Capabilities)),
            ("DecisionRequest", schema_for!(DecisionRequest)),
            ("DecisionResult", schema_for!(DecisionResult)),
            ("HealthReport", schema_for!(HealthReport)),
            ("Primitive", schema_for!(Primitive)),
            ("PrimitiveKind", schema_for!(PrimitiveKind)),
            ("ProviderMeta", schema_for!(ProviderMeta)),
            ("Question", schema_for!(Question)),
            ("Usage", schema_for!(Usage)),
        ];
        assert_eq!(schemas.len(), 11);

        for (name, schema) in schemas {
            let json = serde_json::to_string_pretty(&schema).unwrap();
            fs::write(dir.join(format!("{name}.json")), json).unwrap();
        }
    }
}
